### PR TITLE
Force curl cookbook to be retrieved

### PR DESCRIPTION
**Pull request by jujugrrr**
Newrelic cookbook simply recommends `curl`, but `berks upload` will fail without it.

https://github.com/berkshelf/berkshelf/issues/1216 (see my comment)
https://github.com/berkshelf/berkshelf/issues/1362

Not sure the tests I've done on this PR are relevant, I just wanted to be sure I was testing the bug.

How to reproduce on master(be careful to use your own organisation for the berks upload) : 
```
#to be sure you have a clean berkshelf https://github.com/berkshelf/berkshelf/issues/1362
mv ~/.berkshelf/cookbooks/newrelic* /tmp/
rm Berksfile.lock && berks install
# at this point `curl` should not be there when doing `berks show curl`, which will break `berks upload`
berks upload
Dependency 'curl' was not found. Please make sure it is in your Berksfile, and then run `berks install` to download and install the missing dependencies.
```

### CODE REVIEW

**Comment by martinb3** [comment]
@jujugrrr Hello! I've seen the newrelic cookbook be very willing to accept PRs. Can we try to submit one to them?

**Comment by martinb3** [comment]
Also, I wish there was a better way to test this than run berks install and check the output. :(

**Comment by jujugrrr** [comment]
> @jujugrrr Hello! I've seen the newrelic cookbook be very willing to accept PRs. Can we try to submit one to them?

it looks like a weird behavior from Berkshelf, `berks upload` needs the recommends, but `berks install` doesn't get them.
https://github.com/berkshelf/berkshelf/issues/1362

>Also, I wish there was a better way to test this than run berks install and check the output. :(

:+1: 

> Not sure the tests I've done on this PR are relevant, I just wanted to be sure I was testing the bug.

I have no idea how to test it without digging in Berkshelf library

**Comment by martinb3** [comment]
I submitted the change to the newrelic cookbook: https://github.com/escapestudios-cookbooks/newrelic/pull/148

I guess we'll see what they say. In the mean time, this LGTM if you want to merge it (just not sure if you were ready for a merge).

**Comment by jujugrrr** [comment]
Let's see if we get feedback from newrelic :-)

**Comment by jujugrrr** [comment]
Closing as it has been applied upstream

**Pull request closed without merging**
