### PR TITLE
added search to iptables setup in memcached

### PR DESCRIPTION
**Pull request by cybermerc**
added search function to limit iptables rules for memcached to make it more secure per issue # 70

### CODE REVIEW

**Comment by cybermerc** [comment]
retest this please

**Comment by cybermerc** [comment]
anyone help me understand this fail:

Use `bundle show [gemname]` to see where a bundled gem is installed.
+ bundle exec rake style
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.5-compliant syntax, but you are running 2.1.2.
RuboCop failed!

**Comment by cybermerc** [comment]
killing since it appears Thode also fixed this bug...

**Comment by prometheanfire** [comment]
sorry, think we crossed wires on this, if you want it can be merged #92

**Pull request closed without merging**
