### PR TITLE
Percona recipe addition

### PR DESCRIPTION
**Pull request by cybermerc**
adds percona master/slave recipes as well as updates to metadata, README and CHANGELOG

### CODE REVIEW

**Comment by cybermerc** [comment]
retest this please

**Comment by theborch** [comment]
retest this please

**Comment by theborch** [comment]
retest this please

**Comment by theborch** [comment]
retest this please

**Comment by theborch** [comment]
retest this please

**Comment by cybermerc** [comment]
repairing

**Pull request closed without merging**
