### PR TITLE
Pinned down OpenSSL cookbook as the module namespace changed, and there is a typo ...

### PR DESCRIPTION
**Pull request by jujugrrr**
...https://github.com/opscode-cookbooks/openssl/commit/03e0e9b690fd9db3d81779762c810371f0fe7e1e

Currently it breaks stack_commons : 
```
uninitialized constant Opscode::OpenSSL

Cookbook Trace:
---------------
  /var/folders/0p/l33795bn35ng4f_6p_7sqtbm2tcccx/T/d20150219-8002-1sff3tz/cookbooks/percona/attributes/default.rb:6:in `from_file'
```

### CODE REVIEW

**Comment by jujugrrr** [comment]
Build error comes from #108

**Comment by jujugrrr** [comment]
@martinb3 / @lmunro Could you look at the logstash related build errors?

**Comment by prometheanfire** [comment]
does it have to be 2.0.0?

**Comment by jujugrrr** [comment]
I think they changed the namespace and it was not changed on Percona. They reverted the change on OpenSSL cookbook though, so we don't need 2.0.0 anymore (until they change it back :wink: )

**Comment by martinb3** [comment]
@jujugrrr I don't see any logstash-related build errors -- could you point me at what you're referring to?

**Comment by martinb3** [comment]
retest this please

**Comment by martinb3** [comment]
I pushed a newer commit that fixes the serverspec issues. It's actually a bug introduced recently in serverspec where it can't correctly detect if an upstart service is enabled now (https://github.com/serverspec/specinfra/pull/326). I also cleaned up the elkstack deps.

Finally, I heard the OpenSSL change was reverted, so maybe we don't need the pinning anymore? @jujugrrr what do you think?

**Comment by prometheanfire** [comment]
the code changes lgtm

:+1:

**Pull request merged**
