### PR TITLE
including mysql_chef_gem automatically now

### LINKED ISSUE #107: Need to include mysql2_chef_gem directly
```
Chef::Exceptions::RecipeNotFound
--------------------------------
could not find recipe mysql for cookbook database
```
'Cause it was removed: opscode-cookbooks/database@b1941c6

### PR DESCRIPTION
**Pull request by prometheanfire**
It was removed from the database cookbook, talked with @someara about it
and we need to include the gem directly from now on.

fixes #107

Signed-off-by: Matthew Thode <mthode@mthode.org>

### CODE REVIEW

**Comment by jujugrrr** [comment]
retest this pelase

**Comment by jujugrrr** [comment]
retest this pelase

**Comment by jujugrrr** [comment]
I've merged this change to #109 as they depend on each other

**Comment by someara** [comment]
Ps, the latest version of the database cookbook is written against mysql2_chef_gem



—

**Comment by jujugrrr** [comment]
> Ps, the latest version of the database cookbook is written against mysql2_chef_gem

Thanks for the update :wink:

**Pull request closed without merging**
