### PR TITLE
small issue fixes

### PR DESCRIPTION
**Pull request by prometheanfire**

### CODE REVIEW

**Comment by jujugrrr** [comment]
I love the set_unless to default_unless. It's a breaking change though? Maybe we should have an upgrade path in the changelog and send an email about it

**Comment by prometheanfire** [comment]
Don't think it's a breaking change at all.  just lowers the priority of our assignments, any overrides will still work.

**Comment by jujugrrr** [comment]
If before I was doing `normal['stack_commons']['mysql']['databases']['db1']...` will the `default_unless['stack_commons']['mysql']['databases']` create the [default attribute](https://github.com/rackspace-cookbooks/stack_commons/blob/a77f1060ec1376c395b9a420de88b6b9989dae07/recipes/mysql_base.rb#L166-L169) ?

I think you are right though, as even if it creates the default attribute, the one with `normal` should have precedence. I'm not 100% sure, as Chef and attributes might be surprising sometime.

**Comment by prometheanfire** [comment]
I'm fairly sure we will be fine.  This is the lowest priority we can do an _unless in a recipe.  So we moved in the right direction if anything.

**Pull request merged**
